httpserver: 
    ip: 127.0.0.1
    port: 8080
    allowed_ips_by_cors:
        - http://localhost:4201

smtp:
    host: smtp.gmail.com
    port: 587
    username: your_username
    password: your_password