httpserver: 
    ip: 127.0.0.1
    port: 8080
    allowed_ips_by_cors:
        - http://localhost

authserver:
    ip: 127.0.0.1
    port: 8081

smtpserver:
    ip: 127.0.0.1
    port: 8082

postgres:
    ip: 127.0.0.1
    port: 5432
    dbname: test
    user: test
    password: test

smtp:
    host: smtp.gmail.com
    port: 587
    username: test
    password: test

pop3:
    host: pop.gmail.com
    port: 995
    username: test
    password: test 

redis:
    ip: 127.0.0.1
    port: 6379
    dbnum: 0
    user: test
    password: test
    
