httpserver: 
    ip: localhost
    port: 8080
    allowed_ips_by_cors:
        - https://89.208.228.234
        - http://89.208.228.234
        - http://localhost
        - https://localhost
        - https://giga-mail.ru
        - http://giga-mail.ru
        - http://localhost:3000
        - https://localhost:3000


authserver:
    ip: localhost
    port: 8081

smtpserver:
    ip: localhost
    port: 8082

postgres:
    ip: localhost
    port: 5432
    dbname: test
    user: test
    password: test

smtp:
    host: smtp.gmail.com
    port: 587
    username: test
    password: test

pop3:
    host: pop.gmail.com
    port: 995
    username: test
    password: test 

redis:
    ip: localhost
    port: 6379
    dbnum: 0
    user: test
    password: test
    
