version: '3.9'

services:
  postgres:
    image: postgres:latest
    #build: ../postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - ../postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command: postgres -c config_file=../postgres/db.conf
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
  
  